#!/bin/sh
# Usage: btsync-secret
# A Bittorrent Sync RW Secret Generator
set -e

rand_binary=""
new_secret=""

# cd to the current script's folder
cd "$(dirname "$0")"

function gen_base32_secret() {
    rand_binary=`head -c20 /dev/random`
    new_secret=`python -c "import base64; print base64.b32encode('''$rand_binary''')"`
    case "$new_secret" in
        *=*) gen_base32_secret ;;
    esac
}

gen_base32_secret

echo 'btsyncsecret = "A'$new_secret'"' > values.toml

helm tpl -o ../manifests/deis-minio-sync-secret.yaml -d values.toml deis-minio-sync-secret.yaml
